services:
  postgres:
    image: postgres:13
    platform: linux/amd64
    environment:
      POSTGRES_DB: twitter_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - airflow-network

  zookeeper:
    image: zookeeper:3.7
    platform: linux/amd64
    ports:
      - "2181:2181"
    networks:
      - airflow-network

  kafka:
    image: confluentinc/cp-kafka:latest
    platform: linux/amd64
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    depends_on:
      - zookeeper
    networks:
      - airflow-network

  airflow:
    image: apache/airflow:2.5.0
    platform: linux/amd64
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://user:password@postgres/twitter_db
      AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: "True"
      AIRFLOW__CORE__FERNET_KEY: 'YOUR_FERNEY_KEY'  # Gantilah dengan kunci Fernet yang dihasilkan
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"      # Opsional
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka
      - zookeeper
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    networks:
      - airflow-network
    command: ["airflow", "webserver"]

  airflow-init:
    image: apache/airflow:2.5.0
    platform: linux/amd64
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://user:password@postgres/twitter_db
    depends_on:
      - postgres
    networks:
      - airflow-network
    command: airflow db init  # Ubah dari list ke string

networks:
  airflow-network:
    driver: bridge